Update Lustre e2fsprogs for v1.41.14 release
This patch contains a number of changes, some of them related to
updating to the upstream e2fsprogs 1.41.14 release, and some of
them are cleanups that should probably be in a separate patch
but are included here only because of my newness to the patch
management process.  In particular, the non-update changes are:

* Add "Obsoletes: e4fsprogs" to avoid RPM installation conflicts
  on RHEL5.x systems where e4fsprogs is installed.
* Move RPM .spec improvements earlier in the patch series than -lfsck
* Remove patches to configure, and instead --enable-maintainer-mode
  is enabled by default so that changes to configure.in cause the
  configure script to be regenerated.  This has the unfortunate
  side-effect of leaving uncommitted changes in the configure
  script, which is now added to our .gitignore file.
* Add checks for db4.7 and db4.8 so lfsck can build on new distros
* Add basic regression tests for large xattr support
* Fix f_random_corruption to correctly mount ext4 filesystems in test
* Quiet some build warnings, though several new ones appear in the
  base code and our patches with a newer version of GCC
* Shorten the name of some tests so they don't line wrap when running
* Use tabs instead of spaces for indenting in our patches

Change-Id: I35a6a652bf3f6ae8c414002cad7d63e9b958c114

diff --git a/patches/e2fsprogs-tests-f_mmp.patch b/patches/e2fsprogs-tests-f_mmp.patch
--- a/patches/e2fsprogs-tests-f_mmp.patch
+++ b/patches/e2fsprogs-tests-f_mmp.patch
@@ -49,8 +49,8 @@ Index: e2fsprogs-1.41.10/tests/f_mmp_off/script
 +
 +stat -f $TMPFILE | grep "Type: tmpfs" > /dev/null
 +if [ $? == 0 ] ; then
-+        echo "skipped for tmpfs (no O_DIRECT support)"
-+        return 0
++	echo "skipped for tmpfs (no O_DIRECT support)"
++	return 0
 +fi
 +
 +$MKE2FS -q -F -o Linux -b 1024 -O mmp $TMPFILE 100 > $test_name.log 2>&1
@@ -90,8 +90,8 @@ Index: e2fsprogs-1.41.10/tests/f_mmp_on/script
 +
 +stat -f $TMPFILE | grep "Type: tmpfs" > /dev/null
 +if [ $? == 0 ] ; then
-+        echo "skipped for tmpfs (no O_DIRECT support)"
-+        return 0
++	echo "skipped for tmpfs (no O_DIRECT support)"
++	return 0
 +fi
 +
 +$MKE2FS -q -F -o Linux -b 1024 $TMPFILE 100 > $test_name.log 2>&1
@@ -131,8 +131,8 @@ Index: e2fsprogs-1.41.10/tests/f_mmp_corrupt/script
 +
 +stat -f $TMPFILE | grep "Type: tmpfs" > /dev/null
 +if [ $? == 0 ] ; then
-+        echo "skipped for tmpfs (no O_DIRECT support)"
-+        return 0
++	echo "skipped for tmpfs (no O_DIRECT support)"
++	return 0
 +fi
 +
 +echo "make the test image ..." > $test_name.log
@@ -140,7 +140,7 @@ Index: e2fsprogs-1.41.10/tests/f_mmp_corrupt/script
 +status=$?
 +if [ "$status" != 0 ] ; then
 +	echo "mke2fs -O mmp failed" >  $test_name.failed
-+        exit 1
++	exit 1
 +fi
 +
 +# create a corrupted image
@@ -153,15 +153,15 @@ Index: e2fsprogs-1.41.10/tests/f_mmp_corrupt/script
 +$FSCK $FSCK_OPT $TMPFILE >> $test_name.log 2>&1
 +status=$?
 +if [ "$status" != 0 ] ; then
-+        echo "the second fsck ..." >> $test_name.log
-+        $FSCK $FSCK_OPT $TMPFILE >> $test_name.log 2>&1
-+        status=$?
-+        if  [ "$status" = 0 ] ; then
-+            echo "ok"
-+            touch $test_name.ok
-+        else
-+            echo "the second fsck with corrupted mmp failed" >  $test_name.failed
-+        fi
++	echo "the second fsck ..." >> $test_name.log
++	$FSCK $FSCK_OPT $TMPFILE >> $test_name.log 2>&1
++	status=$?
++	if  [ "$status" = 0 ] ; then
++	    echo "ok"
++	    touch $test_name.ok
++	else
++	    echo "the second fsck with corrupted mmp failed" >  $test_name.failed
++	fi
 +else
 +	echo "the first fsck with corrupted mmp failed" >  $test_name.failed
 +fi
diff --git a/patches/e2fsprogs-tests-f_random_corruption.patch b/patches/e2fsprogs-tests-f_random_corruption.patch
--- a/patches/e2fsprogs-tests-f_random_corruption.patch
+++ b/patches/e2fsprogs-tests-f_random_corruption.patch
@@ -29,11 +29,11 @@ bug, this part of the test is not enabled by default.
 Signed-off-by: Andreas Dilger <adilger@clusterfs.com>
 Signed-off-by: Kalpak Shah <kalpak@clusterfs.com>
 
-Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
+Index: e2fsprogs-1.41.14/tests/f_random_corruption/script
 ===================================================================
 --- /dev/null
-+++ e2fsprogs-1.41.10/tests/f_random_corruption/script
-@@ -0,0 +1,273 @@
++++ e2fsprogs-1.41.14/tests/f_random_corruption/script
+@@ -0,0 +1,272 @@
 +# This is to make sure that if this test fails other tests can still be run
 +# instead of doing an exit. We break before the end of the loop.
 +export LOOP_COUNT=${LOOP_COUNT:-1}
@@ -107,18 +107,17 @@ Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
 +fi
 +
 +modprobe ext4 2> /dev/null
-+modprobe ext4dev 2> /dev/null
 +
 +# If ext4 is present in the kernel then we can play with ext4 options
 +EXT4=`grep ext4 /proc/filesystems 2> /dev/null`
 +if [ -n "$EXT4" ]; then
 +	USE_EXT4=$((RANDOM % 2 ))
 +	if (( USE_EXT4 == 1 )); then
-+		FS_TYPE="ext4dev"
++		FS_TYPE="ext4"
 +	fi
 +fi
 +
-+if [ "$FS_TYPE" = "ext4dev" ]; then
++if [ "$FS_TYPE" = "ext4" ]; then
 +	UNINIT_GROUPS=$((RANDOM % 12 ))
 +	if (( UNINIT_GROUPS == 0 )); then
 +		FEATURES=$FEATURES,uninit_bg
@@ -158,7 +157,7 @@ Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
 +	[ -d $MNTPT ] && rmdir $MNTPT
 +	cp $OUT $OUT.$DATE
 +	echo " failed"
-+	echo "*** This appears to be a bug in e2fsprogs ***"
++	echo "error: *** This appears to be a bug in e2fsprogs ***"
 +	echo "Please contact linux-ext4@vger.kernel.org for further assistance."
 +	echo "Include $OUT.$DATE, and save $ARCHIVE locally for reference."
 +	unset_vars
@@ -227,14 +226,14 @@ Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
 +		log "Failed to create or find mountpoint...."
 +	else
 +		mount -t $FS_TYPE $MOUNT_OPTS $IMAGE $MNTPT 2>&1 | tee -a $OUT
-+		if [ $? -ne 0 ]; then
-+			log "Unable to mount file system - skipped"
++		if [ ${PIPESTATUS[0]} -ne 0 ]; then
++			log "Error mounting file system - skipped"
 +		else
 +			df -h $MNTPT >> $OUT
 +			df -i $MNTPT >> $OUT
 +			log "Copying data into the test filesystem..."
 +
-+			cp -r ../ $MNTPT >> $OUT 2>&1
++			cp -r ../{.git,lib,misc,e2fsck,po} $MNTPT/ >> $OUT 2>&1
 +			sync
 +			umount -f $MNTPT > /dev/null 2>&1 | tee -a $OUT
 +		fi
@@ -290,7 +289,7 @@ Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
 +
 +if [ "$MOUNT_AFTER_CORRUPTION" = "yes" ]; then
 +	mount -t $FS_TYPE $MOUNT_OPTS $IMAGE $MNTPT 2>&1 | tee -a $OUT
-+	[ $? -ne 0 ] && log "Unable to mount file system - skipped"
++	[ ${PIPESTATUS[0]} -ne 0 ] && log "error mounting file system - skipped"
 +
 +	[ "$REMOVE_FILES" = "yes" ] && rm -rf $MNTPT/* >> $OUT
 +	umount -f $MNTPT > /dev/null 2>&1 | tee -a $OUT
@@ -307,12 +306,12 @@ Index: e2fsprogs-1.41.10/tests/f_random_corruption/script
 +
 +COUNT=$((COUNT + 1))
 +done
-Index: e2fsprogs-1.41.10/tests/Makefile.in
+Index: e2fsprogs-1.41.14/tests/Makefile.in
 ===================================================================
---- e2fsprogs-1.41.10.orig/tests/Makefile.in
-+++ e2fsprogs-1.41.10/tests/Makefile.in
-@@ -27,6 +27,8 @@ mke2fs.conf: $(srcdir)/../misc/mke2fs.co
- 	sed -e 's/blocksize = -1/blocksize = 4096/' $(srcdir)/../misc/mke2fs.conf >mke2fs.conf
+--- e2fsprogs-1.41.14.orig/tests/Makefile.in
++++ e2fsprogs-1.41.14/tests/Makefile.in
+@@ -27,6 +27,8 @@ mke2fs.conf: $(srcdir)/mke2fs.conf.in
+ 	$(CP) $(srcdir)/mke2fs.conf.in mke2fs.conf
  
  check:: test_script
 +	@echo "Removing remnants of earlier tests..."
